In [1]:
import os

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'project.settings')
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"
import django
django.setup()

In [2]:
import pandas as pd
df = pd.read_csv('results.csv')
df = df[(df.tournament == 'UEFA Euro') & (df.date > '2024-01-01')]

In [3]:
df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
47075,2024-06-14,Germany,Scotland,NaN,NaN,UEFA Euro,Munich,Germany,False
47076,2024-06-15,Hungary,Switzerland,NaN,NaN,UEFA Euro,Cologne,Germany,True
47077,2024-06-15,Spain,Croatia,NaN,NaN,UEFA Euro,Berlin,Germany,True
47078,2024-06-15,Italy,Albania,NaN,NaN,UEFA Euro,Dortmund,Germany,True
47079,2024-06-16,Slovenia,Denmark,NaN,NaN,UEFA Euro,Stuttgart,Germany,True

In [3]:
th = df['home_team'].dropna().unique()
ta = df['away_team'].dropna().unique()

team_names = set(th) | set(ta)

teams = sorted(list(team_names))
teams

['Albania',
 'Austria',
 'Belgium',
 'Croatia',
 'Czech Republic',
 'Denmark',
 'England',
 'France',
 'Georgia',
 'Germany',
 'Hungary',
 'Italy',
 'Netherlands',
 'Poland',
 'Portugal',
 'Romania',
 'Scotland',
 'Serbia',
 'Slovakia',
 'Slovenia',
 'Spain',
 'Switzerland',
 'Turkey',
 'Ukraine']

In [4]:
# groupe = [chr(ord('A')+(i)%6) for i in range(0,18)]
groups = pd.read_csv('groups.csv')
groups

    Stage Group            Team
0   Group     A         Germany
1   Group     A        Scotland
2   Group     A         Hungary
3   Group     A     Switzerland
4   Group     B           Spain
5   Group     B         Croatia
6   Group     B           Italy
7   Group     B         Albania
8   Group     C        Slovenia
9   Group     C         Denmark
10  Group     C          Serbia
11  Group     C         England
12  Group     D          Poland
13  Group     D     Netherlands
14  Group     D         Austria
15  Group     D          France
16  Group     E         Belgium
17  Group     E        Slovakia
18  Group     E         Romania
19  Group     E         Ukraine
20  Group     F          Turkey
21  Group     F         Georgia
22  Group     F        Portugal
23  Group     F  Czech Republic

In [5]:

from django.contrib.auth.models import User
from UI.models import Team, Groupe

In [6]:
from UI.models import Tournament
uefa2024 = Tournament()
uefa2024.name = 'European Soccer Championship UEFA 2024'
Tournament.save(uefa2024)

In [7]:

uefa2024 = Tournament.objects.all()[0]

In [8]:
uefa2024.name

'European Soccer Championship UEFA 2024'

In [9]:
Groupe.objects.all().delete()

(0, {})

In [10]:
from UI.models import Groupe

for n in Groupe.GROUPE_NAMES:
    g = Groupe()
    g.name = n
    g.tournament = uefa2024
    Groupe.save(g)

In [11]:
for g in Groupe.objects.all():
    print(g.name, g.tournament.name)

A European Soccer Championship UEFA 2024
B European Soccer Championship UEFA 2024
C European Soccer Championship UEFA 2024
D European Soccer Championship UEFA 2024
E European Soccer Championship UEFA 2024
F European Soccer Championship UEFA 2024

In [12]:
groupe_dict = dict()
all_groupes = Groupe.objects.all()
for t in groups['Team']:
    g = groups[groups['Team']==t]['Group'].values[0]
    i = ord(g)-ord('A')
    group = all_groupes[i]
    groupe_dict[t] = group

groupe_dict['England'].name

'C'

In [13]:
for i, t in enumerate(teams):
    team = Team()
    team.id = i
    team.name = t
    team.groupe = groupe_dict[t]
    Team.save(team)

In [14]:
for t in Team.objects.all():
    print(t.id, t.name, t.groupe.name)

0 Albania B
1 Austria D
2 Belgium E
3 Croatia B
4 Czech Republic F
5 Denmark C
6 England C
7 France D
8 Georgia F
9 Germany A
10 Hungary A
11 Italy B
12 Netherlands D
13 Poland D
14 Portugal F
15 Romania E
16 Scotland A
17 Serbia C
18 Slovakia E
19 Slovenia C
20 Spain B
21 Switzerland A
22 Turkey F
23 Ukraine E

In [15]:
team_dict = dict()
for t in Team.objects.all():
    team_dict[t.name] = t

In [16]:
vorrunde = df[:36]
vorrunde

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
47075,2024-06-14,Germany,Scotland,NaN,NaN,UEFA Euro,Munich,Germany,False
47076,2024-06-15,Hungary,Switzerland,NaN,NaN,UEFA Euro,Cologne,Germany,True
47077,2024-06-15,Spain,Croatia,NaN,NaN,UEFA Euro,Berlin,Germany,True
47078,2024-06-15,Italy,Albania,NaN,NaN,UEFA Euro,Dortmund,Germany,True
47079,2024-06-16,Slovenia,Denmark,NaN,NaN,UEFA Euro,Stuttgart,Germany,True
47080,2024-06-16,Serbia,England,NaN,NaN,UEFA Euro,Gelsenkirchen,Germany,True
47081,2024-06-16,Poland,Netherlands,NaN,NaN,UEFA Euro,Hamburg,Germany,True
47082,2024-06-17,Austria,France,NaN,NaN,UEFA Euro,Düsseldorf,Germany,True
47083,2024-06-17,Romania,Ukraine,NaN,NaN,UEFA Euro,Munich,Germany,True
47084,2024-06-17,Belgium,Slovakia,NaN,NaN,UEFA Euro,Frankfurt,Germany,True
47085,2024-06-18,Turkey,Georgia,NaN,NaN,UEFA Euro,Dortmund,Germany,True
47086,2024-06-18,Portugal,Czech Republic,NaN,NaN,UEFA Euro,Leipzig,Germany,True
47087,2024-06-19,Germany,Hungary,NaN,NaN,UEFA Euro,Stuttgart,Germany,False
47088,2024-06-19,Scotland,Switzerland,NaN,NaN,UEFA Euro,Cologne,Germany,True
47089,2024-06-19,Croatia,Albania,NaN,NaN,UEFA Euro,Hamburg,Germany,True
47090,2024-06-20,Spain,Italy,NaN,NaN,UEFA Euro,Gelsenkirchen,Germany,True
47091,2024-06-20,Slovenia,Serbia,NaN,NaN,UEFA Euro,Munich,Germany,True
47092,2024-06-20,Denmark,England,NaN,NaN,UEFA Euro,Frankfurt,Germany,True
47093,2024-06-21,Poland,Austria,NaN,NaN,UEFA Euro,Berlin,Germany,True
47094,2024-06-21,Netherlands,France,NaN,NaN,UEFA Euro,Leipzig,Germany,True
47095,2024-06-21,Slovakia,Ukraine,NaN,NaN,UEFA Euro,Düsseldorf,Germany,True
47096,2024-06-22,Belgium,Romania,NaN,NaN,UEFA Euro,Cologne,Germany,True
47097,2024-06-22,Georgia,Czech Republic,NaN,NaN,UEFA Euro,Hamburg,Germany,True
47098,2024-06-22,Turkey,Portugal,NaN,NaN,UEFA Euro,Dortmund,Germany,True
47099,2024-06-23,Germany,Switzerland,NaN,NaN,UEFA Euro,Frankfurt,Germany,False
47100,2024-06-23,Scotland,Hungary,NaN,NaN,UEFA Euro,Stuttgart,Germany,True
47101,2024-06-24,Albania,Spain,NaN,NaN,UEFA Euro,Düsseldorf,Germany,True
47102,2024-06-24,Croatia,Italy,NaN,NaN,UEFA Euro,Leipzig,Germany,True
47103,2024-06-25,England,Slovenia,NaN,NaN,UEFA Euro,Cologne,Germany,True
47104,2024-06-25,Denmark,Serbia,NaN,NaN,UEFA Euro,Munich,Germany,True
47105,2024-06-25,Netherlands,Austria,NaN,NaN,UEFA Euro,Berlin,Germany,True
47106,2024-06-25,France,Poland,NaN,NaN,UEFA Euro,Dortmund,Germany,True
47107,2024-06-26,Slovakia,Romania,NaN,NaN,UEFA Euro,Frankfurt,Germany,True
47108,2024-06-26,Ukraine,Belgium,NaN,NaN,UEFA Euro,Stuttgart,Germany,True
47109,2024-06-26,Georgia,Portugal,NaN,NaN,UEFA Euro,Gelsenkirchen,Germany,True
47110,2024-06-26,Czech Republic,Turkey,NaN,NaN,UEFA Euro,Hamburg,Germany,True

In [17]:
from UI.models import Match
from datetime import datetime

datum = vorrunde['date']
home_teams = vorrunde['home_team']
away_teams = vorrunde['away_team']

In [18]:
Match.objects.all().delete()
Match.__init__

for m in Match.objects.all():
    print(m.id, m.home_team.name, m.away_team.name)

In [19]:
for i in home_teams.index:
        _match = Match()
        _match.date = datetime.strptime(datum[i],'%Y-%m-%d').date()
        _match.home_team = team_dict[home_teams[i]]
        _match.away_team = team_dict[away_teams[i]]
        _match.match_type = Match.MATCH_TYPES[Match.PRELIMENARY]
        _match.tournament = uefa2024
        Match.save(_match)

In [20]:

for m in Match.objects.all():
    print(m.id, m.date, m.match_type, m.home_team.name,':', m.away_team.name)

1 2024-06-14 prelimenary Germany : Scotland
2 2024-06-15 prelimenary Hungary : Switzerland
3 2024-06-15 prelimenary Spain : Croatia
4 2024-06-15 prelimenary Italy : Albania
5 2024-06-16 prelimenary Slovenia : Denmark
6 2024-06-16 prelimenary Serbia : England
7 2024-06-16 prelimenary Poland : Netherlands
8 2024-06-17 prelimenary Austria : France
9 2024-06-17 prelimenary Romania : Ukraine
10 2024-06-17 prelimenary Belgium : Slovakia
11 2024-06-18 prelimenary Turkey : Georgia
12 2024-06-18 prelimenary Portugal : Czech Republic
13 2024-06-19 prelimenary Germany : Hungary
14 2024-06-19 prelimenary Scotland : Switzerland
15 2024-06-19 prelimenary Croatia : Albania
16 2024-06-20 prelimenary Spain : Italy
17 2024-06-20 prelimenary Slovenia : Serbia
18 2024-06-20 prelimenary Denmark : England
19 2024-06-21 prelimenary Poland : Austria
20 2024-06-21 prelimenary Netherlands : France
21 2024-06-21 prelimenary Slovakia : Ukraine
22 2024-06-22 prelimenary Belgium : Romania
23 2024-06-22 prelimenary Georgia : Czech Republic
24 2024-06-22 prelimenary Turkey : Portugal
25 2024-06-23 prelimenary Germany : Switzerland
26 2024-06-23 prelimenary Scotland : Hungary
27 2024-06-24 prelimenary Albania : Spain
28 2024-06-24 prelimenary Croatia : Italy
29 2024-06-25 prelimenary England : Slovenia
30 2024-06-25 prelimenary Denmark : Serbia
31 2024-06-25 prelimenary Netherlands : Austria
32 2024-06-25 prelimenary France : Poland
33 2024-06-26 prelimenary Slovakia : Romania
34 2024-06-26 prelimenary Ukraine : Belgium
35 2024-06-26 prelimenary Georgia : Portugal
36 2024-06-26 prelimenary Czech Republic : Turkey

In [21]:
import django

django.__version__

'5.0.6'

In [22]:
tournament = Tournament.objects.all()[0]
tournament.name

'European Soccer Championship UEFA 2024'

In [25]:
for m in tournament.match_set.all():
    print(m.id,m.match_type, m.date, m.home_team.name, ':', m.away_team.name)

1 prelimenary 2024-06-14 Germany : Scotland
2 prelimenary 2024-06-15 Hungary : Switzerland
3 prelimenary 2024-06-15 Spain : Croatia
4 prelimenary 2024-06-15 Italy : Albania
5 prelimenary 2024-06-16 Slovenia : Denmark
6 prelimenary 2024-06-16 Serbia : England
7 prelimenary 2024-06-16 Poland : Netherlands
8 prelimenary 2024-06-17 Austria : France
9 prelimenary 2024-06-17 Romania : Ukraine
10 prelimenary 2024-06-17 Belgium : Slovakia
11 prelimenary 2024-06-18 Turkey : Georgia
12 prelimenary 2024-06-18 Portugal : Czech Republic
13 prelimenary 2024-06-19 Germany : Hungary
14 prelimenary 2024-06-19 Scotland : Switzerland
15 prelimenary 2024-06-19 Croatia : Albania
16 prelimenary 2024-06-20 Spain : Italy
17 prelimenary 2024-06-20 Slovenia : Serbia
18 prelimenary 2024-06-20 Denmark : England
19 prelimenary 2024-06-21 Poland : Austria
20 prelimenary 2024-06-21 Netherlands : France
21 prelimenary 2024-06-21 Slovakia : Ukraine
22 prelimenary 2024-06-22 Belgium : Romania
23 prelimenary 2024-06-22 Georgia : Czech Republic
24 prelimenary 2024-06-22 Turkey : Portugal
25 prelimenary 2024-06-23 Germany : Switzerland
26 prelimenary 2024-06-23 Scotland : Hungary
27 prelimenary 2024-06-24 Albania : Spain
28 prelimenary 2024-06-24 Croatia : Italy
29 prelimenary 2024-06-25 England : Slovenia
30 prelimenary 2024-06-25 Denmark : Serbia
31 prelimenary 2024-06-25 Netherlands : Austria
32 prelimenary 2024-06-25 France : Poland
33 prelimenary 2024-06-26 Slovakia : Romania
34 prelimenary 2024-06-26 Ukraine : Belgium
35 prelimenary 2024-06-26 Georgia : Portugal
36 prelimenary 2024-06-26 Czech Republic : Turkey

In [27]:
%pip install lxml

Collecting lxml
  Downloading lxml-5.2.2-cp311-cp311-macosx_10_9_universal2.whl (8.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 10.8 MB/s eta 0:00:0000:0100:01
Installing collected packages: lxml
Successfully installed lxml-5.2.2

[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [28]:
df_italien = pd.read_html('https://sportdaten.n-tv.de/fussball/te1065/italien/kader/')

In [31]:
df_albanien = pd.read_html('https://fbref.com/en/squads/b44b9eb7/Albania-Men-Stats')

In [37]:
df_albanien[1].describe()

              GF         GA       Poss   Attendance  Notes
count  12.000000  12.000000   8.000000     10.00000    0.0
mean    1.500000   0.750000  50.125000  19022.10000    NaN
std     1.314257   0.866025  12.426211  15362.66965    NaN
min     0.000000   0.000000  36.000000    200.00000    NaN
25%     0.000000   0.000000  42.000000  11625.75000    NaN
50%     1.500000   1.000000  47.000000  19779.00000    NaN
75%     3.000000   1.000000  55.750000  21328.00000    NaN
max     3.000000   3.000000  72.000000  56227.00000    NaN

In [30]:
df_italien

[                 Nr.        Unnamed: 1                   Name  \
 0            Torwart           Torwart                Torwart
 1                  1               NaN   Gianluigi Donnarumma
 2                 21               NaN             Alex Meret
 3                 12               NaN      Guglielmo Vicario
 4             Abwehr            Abwehr                 Abwehr
 5                 23               NaN     Alessandro Bastoni
 6                 19               NaN        Raoul Bellanova
 7                  4               NaN  Alessandro Buongiorno
 8                 15               NaN     Riccardo Calafiori
 9                 13               NaN         Matteo Darmian
 10                 2               NaN    Giovanni Di Lorenzo
 11                 3               NaN       Federico Dimarco
 12                25               NaN         Federico Gatti
 13                 5               NaN       Gianluca Mancini
 14        Mittelfeld        Mittelfeld             Mittelfeld
 15                 6               NaN         Nicolò Barella
 16                24               NaN        Andrea Cambiaso
 17                16               NaN        Bryan Cristante
 18                18               NaN         Nicolò Fagioli
 19                26               NaN     Michael Folorunsho
 20                 7               NaN        Davide Frattesi
 21                 8               NaN               Jorginho
 22                10               NaN     Lorenzo Pellegrini
 23                20               NaN        Mattia Zaccagni
 24             Sturm             Sturm                  Sturm
 25                14               NaN        Federico Chiesa
 26                22               NaN    Stephan El Shaarawy
 27                11               NaN      Giacomo Raspadori
 28                 9               NaN          Mateo Retegui
 29                17               NaN      Gianluca Scamacca
 30           Trainer           Trainer                Trainer
 31               NaN               NaN      Luciano Spalletti
 32        Co-Trainer        Co-Trainer             Co-Trainer
 33               NaN               NaN      Marco Domenichini
 34   Torwart-Trainer   Torwart-Trainer        Torwart-Trainer
 35               NaN               NaN         Marco Savorani
 36  Athletik-Trainer  Athletik-Trainer       Athletik-Trainer
 37               NaN               NaN      Francesco Sinatti

               Verein             Verein.1        Geburtstag
 0            Torwart              Torwart           Torwart
 1                NaN  Paris Saint-Germain        25.02.1999
 2                NaN           SSC Neapel        22.03.1997
 3                NaN    Tottenham Hotspur        07.10.1996
 4             Abwehr               Abwehr            Abwehr
 5                NaN        Inter Mailand        13.04.1999
 6                NaN             FC Turin        17.05.2000
 7                NaN             FC Turin        06.06.1999
 8                NaN           Bologna FC        19.05.2002
 9                NaN        Inter Mailand        02.12.1989
 10               NaN           SSC Neapel        04.08.1993
 11               NaN        Inter Mailand        10.11.1997
 12               NaN       Juventus Turin        24.06.1998
 13               NaN               AS Rom        17.04.1996
 14        Mittelfeld           Mittelfeld        Mittelfeld
 15               NaN        Inter Mailand        07.02.1997
 16               NaN       Juventus Turin        20.02.2000
 17               NaN               AS Rom        03.03.1995
 18               NaN       Juventus Turin        12.02.2001
 19               NaN        Hellas Verona        07.02.1998
 20               NaN        Inter Mailand        22.09.1999
 21               NaN           Arsenal FC        20.12.1991
 22               NaN               AS Rom        19.06.1996
 23               NaN            Lazio Rom        16.06.1995
 24             Sturm                Sturm             Sturm
 25               NaN       Juventus Turin        25.10.1997
 26               NaN               AS Rom        27.10.1992
 27               NaN           SSC Neapel        18.02.2000
 28               NaN             FC Genua        29.04.1999
 29               NaN             Atalanta        01.01.1999
 30           Trainer              Trainer           Trainer
 31               NaN                  NaN        07.03.1959
 32        Co-Trainer           Co-Trainer        Co-Trainer
 33               NaN                  NaN        21.10.1958
 34   Torwart-Trainer      Torwart-Trainer   Torwart-Trainer
 35               NaN       ACF Fiorentina        31.03.1965
 36  Athletik-Trainer     Athletik-Trainer  Athletik-Trainer
 37               NaN           SSC Neapel               NaN  ]